config:
  accelerator: auto
  atom_fea_len: 64
  batch_size: 128
  decay_power: 1
  devices: auto
  downstream: outputs.pbe.bandgap
  draw_false_grid: false
  drop_rate: 0.1
  end_lr: 0
  exp_name: pretrained_mof
  hid_dim: 768
  img_size: 30
  in_chans: 1
  learning_rate: 0.0001
  load_path: ''
  log_dir: /output
  loss_names:
    bbc: 0
    classification: 0
    ggm: 0
    moc: 0
    mpp: 0
    mtp: 0
    regression: 1
    vfp: 0
  lr_mult: 1
  max_epochs: 100
  max_graph_len: 300
  max_grid_len: -1
  max_nbr_atoms: 12
  max_steps: -1
  mean: 2.0848597828915065
  mlp_ratio: 4
  mpp_ratio: 0.15
  n_classes: 0
  n_targets: 1
  nbr_fea_len: 64
  num_heads: 12
  num_layers: 12
  num_nodes: 1
  num_workers: 16
  optim_type: adamw
  patch_size: 5
  per_gpu_batchsize: 128
  precision: 32
  resume_from: null
  root_dataset: /dataset
  seed: 0
  std: 1.1276775855334698
  test_only: false
  val_check_interval: 1.0
  visualize: false
  warmup_steps: 0.05
  weight_decay: 0.01
